### ISSUE TITLE
Adhere to http://makeapullrequest.com/

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#101]
Read http://makeapullrequest.com/

1. Add a badge to readme
2. update contributing.md

**Comment by ArtisticMemes** [comment]
Pull request #105 meets these requirements

**Comment by scriptnull** [comment]
This is published to npm, so closing.

![image](https://user-images.githubusercontent.com/4211715/36339045-59c4e38c-13e2-11e8-8067-6fc2cceeeed7.png)

@ArtisticMemes thanks :)
