### ISSUE TITLE
Ability to publish serially 

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#46]
right now if we publish, we are publishing parallely. It would be good to have serial publishing

**Comment by argonlaser** [comment]
@scriptnull : Within a github project, we can make it serial execution to ensure proper ordering of issues.
Across github projects it could be parallel. I think thats the requirement @scriptnull

**Comment by scriptnull** [comment]
@argonlaser The idea is to use async.eachLimit or async.series in this line https://github.com/microplan-xyz/microplan/blob/master/microplan-publish.js#L135

So that, the publishing of plan is either serial or parallel. This helps us achieve scenario like
1. publish github issue 1
1. publish github issue 2
1. publish github issue 3
1. publish gitter message # want my gitter message to be sent only after all the github projects are created. So i can use series strategy
