### ISSUE TITLE
Why we have template.yaml inside yaml folder?

### ISSUE THREAD

**Issue by argonlaser** [microplan-xyz/microplan#55]
@scriptnull Instead of cloning init.template.yaml can we clone template.yaml ? So that we could maintain template in corresponding folder as we keep on add support for JSON and TOML.

**Comment by scriptnull** [comment]
yeah. the idea is to move to template.yaml inside the parsers. init.template.yml is temporary.

When more parsers tend to show up, `init` command will take the template file from other formats also. But default should be yaml

**Comment by argonlaser** [comment]
Done in https://github.com/microplan-xyz/microplan/pull/59
