### ISSUE TITLE
microplan alias

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#64]
It would be better, if we had alias inbuilt in the library

`microplan init hello.yml` 

`mp init hello.yml`

**Comment by scriptnull** [comment]
reopening, as I am seeing this error 
![image](https://cloud.githubusercontent.com/assets/4211715/22006660/ff11a8bc-dc92-11e6-9c52-d8339b86a1b6.png)

**Comment by argonlaser** [comment]
The ```alias``` support has to be got from ```commander```. It has been about an year the release has been made. Lets wait for the next release of commander to close this issue.
