### ISSUE TITLE
Custom templates for init command

### ISSUE THREAD

**Issue by scriptnull** [microplan-xyz/microplan#76]
```bash
$ microplan init file.yml --template="./path/to/configuration.file"
```
Currently `init` command uses a predefined path for initializing a plan file. It would be better if we have an option to initialize the file with custom content from user. 

https://github.com/microplan-xyz/microplan/blob/864f033951560b23af6e59bdedffb315bce97b5d/microplan-init.js#L4-L7

This will help in having many template files predefined for projects that people are working on. In my case, I would have a template file for all work related stuff and a template for some side project. Each of those templates would have predefined helpful configurations.

**Comment by dnlup** [comment]
@scriptnull
 Hi, I submitted a  [pull request](https://github.com/microplan-xyz/microplan/pull/77) if you're interested.
Hope it is good for you. 

ps: very interesting project!
