### ISSUE TITLE
create init plan file in a custom directory

### ISSUE THREAD

**Issue by argonlaser** [microplan-xyz/microplan#89]
Currently, ```$ microplan init myplan.yaml``` creates the plan file in the current directory. There should be a flag that should create the plan file in a custom directory.

```$ microplan init myplan.yaml -o ./plans/``` should create the plan file in the plans directory. This flag should be optional.

**Comment by kdembler** [comment]
I can work on this.

**Comment by scriptnull** [comment]
Sure. Go ahead!
