### ISSUE TITLE
Missing `fs-extra` module

### ISSUE THREAD

**Issue by kdembler** [microplan-xyz/microplan#90]
In `microplan-init.js` module `fs-extra` is imported, but it was removed from `package.json` in be065d7
https://github.com/microplan-xyz/microplan/blob/7409cc60c2fbad759a14e64e851255ab8f35b5b5/microplan-init.js#L2

This renders freshly downloaded instance of microplan unusable after `npm install`.

**Comment by scriptnull** [comment]
Thanks for notifying. We will fix this right away and probably add a step in CI process to catch situations like this. 

Let me know if you are planning on opening a PR for this or else, I will fix this right away.
